name: Capture Logs Example

on:
  push:

jobs:
  log-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run azure load test
        id: loadtest
        uses: azure/load-testing@v1
        with: 
          loadTestConfigFile: config.yml
          loadTestResource: test
          resourceGroup: Testing
        continue-on-error: true

      - name: capture and print summary
        run : | 
            steps.loadtest.outputs.stdout | tee -a $GITHUB_ENV
            echo "LOG_OUTPUT=$(cat $GITHUB_ENV)" >> $GITHUB_ENV

      - name: Print log output
        run: echo "${{env.LOG_OUTPUT}}"

      - name: Generate Logs
        id: generate_logs
        run: |
          # Redirect both stdout and stderr to a log file
          {
            echo "Starting the log generation...";
            echo "Running on $(uname -a)";
            echo "Current Date and Time: $(date)";
            echo "Listing files in the current directory:";
            ls -la;
            echo "Log generation completed.";
          } &> generate_logs.txt

      - name: Capture Logs
        id: capture_logs
        run: |
          # Capture the generated logs from the generate_logs.txt file
          cat generate_logs.txt > captured_logs.txt
          echo "Captured logs are saved to captured_logs.txt"

      - name: Upload Captured Logs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: captured-logs
          path: captured_logs.txt

      - name: Display Captured Logs
        run: |
          cat captured_logs.txt
