name: Generate Logs Example

on:
  push:

jobs:
  log-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Generate Logs
        run: |
          echo "Starting the log generation..."
          echo "Running on $(uname -a)"
          echo "Current Date and Time: $(date)"
          echo "Listing files in the current directory:"
          ls -la
          echo "Log generation completed."
